#!/usr/bin/env bash
# oobo-ci.sh — Post AI contribution context on pull requests.
#
# Auto-detects the CI platform and posts (or updates) a PR/MR comment
# with an AI contribution summary generated by `oobo pr`.
#
# Supported platforms: GitHub Actions, GitLab CI, Travis CI, CircleCI,
# Buildkite, Jenkins. Falls back to stdout if the platform can't be
# detected or the required token is missing.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/ooboai/oobo/main/ci/oobo-ci.sh | bash
#
# Environment variables (optional):
#   OOBO_VERSION    — pin a specific release (default: latest)
#   GITHUB_TOKEN    — GitHub PAT or CI token (for GitHub-hosted repos)
#   GITLAB_TOKEN    — GitLab PAT with api scope (for GitLab-hosted repos)
#
# This script never fails the build — all errors are soft.
set -euo pipefail

# ── Install oobo ─────────────────────────────────────────────────────────

install_oobo() {
  if command -v oobo >/dev/null 2>&1; then
    return 0
  fi

  if [ -x "$HOME/.oobo/bin/oobo" ]; then
    export PATH="$HOME/.oobo/bin:$PATH"
    return 0
  fi

  echo "oobo-ci: installing oobo..."
  local install_args="--agent"
  if [ -n "${OOBO_VERSION:-}" ]; then
    OOBO_VERSION="$OOBO_VERSION" curl -fsSL https://oobo.ai/install.sh | bash -s -- $install_args
  else
    curl -fsSL https://oobo.ai/install.sh | bash -s -- $install_args
  fi
  export PATH="$HOME/.oobo/bin:$PATH"
}

# ── Platform detection ───────────────────────────────────────────────────

detect_platform() {
  if [ -n "${GITHUB_ACTIONS:-}" ]; then
    echo "github"
  elif [ -n "${GITLAB_CI:-}" ]; then
    echo "gitlab"
  elif [ -n "${TRAVIS:-}" ]; then
    echo "travis"
  elif [ -n "${CIRCLECI:-}" ]; then
    echo "circleci"
  elif [ -n "${BUILDKITE:-}" ]; then
    echo "buildkite"
  elif [ -n "${JENKINS_URL:-}" ]; then
    echo "jenkins"
  else
    echo "unknown"
  fi
}

# ── Extract PR metadata per platform ─────────────────────────────────────

# Sets: PR_NUMBER, BASE_REF, REPO_SLUG, API_TYPE (github|gitlab), API_URL
extract_pr_metadata() {
  local platform="$1"
  PR_NUMBER=""
  BASE_REF=""
  REPO_SLUG=""
  API_TYPE=""
  API_URL=""

  case "$platform" in
    github)
      if [ -f "${GITHUB_EVENT_PATH:-}" ]; then
        PR_NUMBER=$(python3 -c "import json; e=json.load(open('$GITHUB_EVENT_PATH')); print(e.get('pull_request',{}).get('number',''))" 2>/dev/null || true)
      fi
      BASE_REF="${GITHUB_BASE_REF:-main}"
      REPO_SLUG="${GITHUB_REPOSITORY:-}"
      API_TYPE="github"
      API_URL="https://api.github.com"
      ;;
    gitlab)
      PR_NUMBER="${CI_MERGE_REQUEST_IID:-}"
      BASE_REF="${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-main}"
      REPO_SLUG="${CI_PROJECT_ID:-}"
      API_TYPE="gitlab"
      API_URL="${CI_API_V4_URL:-https://gitlab.com/api/v4}"
      ;;
    travis)
      PR_NUMBER="${TRAVIS_PULL_REQUEST:-}"
      if [ "$PR_NUMBER" = "false" ]; then
        PR_NUMBER=""
      fi
      BASE_REF="${TRAVIS_BRANCH:-main}"
      REPO_SLUG="${TRAVIS_REPO_SLUG:-}"
      API_TYPE="github"
      API_URL="https://api.github.com"
      ;;
    circleci)
      local pr_url="${CIRCLE_PULL_REQUEST:-}"
      if [ -n "$pr_url" ]; then
        PR_NUMBER=$(echo "$pr_url" | grep -oE '[0-9]+$' || true)
        if echo "$pr_url" | grep -q "github.com"; then
          API_TYPE="github"
          API_URL="https://api.github.com"
          REPO_SLUG=$(echo "$pr_url" | sed -E 's|https://github.com/([^/]+/[^/]+)/.*|\1|')
        elif echo "$pr_url" | grep -q "gitlab.com"; then
          API_TYPE="gitlab"
          API_URL="https://gitlab.com/api/v4"
          REPO_SLUG=$(echo "$pr_url" | sed -E 's|https://gitlab.com/([^/]+/[^/]+)/-/.*|\1|')
        fi
      fi
      BASE_REF="main"
      ;;
    buildkite)
      PR_NUMBER="${BUILDKITE_PULL_REQUEST:-}"
      if [ "$PR_NUMBER" = "false" ]; then
        PR_NUMBER=""
      fi
      BASE_REF="${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-main}"
      REPO_SLUG="${BUILDKITE_REPO:-}"
      REPO_SLUG=$(echo "$REPO_SLUG" | sed -E 's|.*github.com[:/]||;s|\.git$||')
      API_TYPE="github"
      API_URL="https://api.github.com"
      ;;
    jenkins)
      PR_NUMBER="${CHANGE_ID:-}"
      BASE_REF="${CHANGE_TARGET:-main}"
      REPO_SLUG="${GIT_URL:-}"
      REPO_SLUG=$(echo "$REPO_SLUG" | sed -E 's|.*github.com[:/]||;s|\.git$||')
      API_TYPE="github"
      API_URL="https://api.github.com"
      ;;
  esac
}

# ── Post comment to GitHub ───────────────────────────────────────────────

post_github_comment() {
  local token="$1" repo="$2" pr="$3" body="$4" tag="$5"

  local existing_id
  existing_id=$(curl -sf \
    -H "Authorization: Bearer $token" \
    -H "Accept: application/vnd.github+json" \
    "${API_URL}/repos/${repo}/issues/${pr}/comments?per_page=100" \
    | python3 -c "
import sys, json
comments = json.load(sys.stdin)
for c in comments:
    if '${tag}' in c.get('body', ''):
        print(c['id'])
        break
" 2>/dev/null || true)

  local json_body
  json_body=$(python3 -c "import json,sys; print(json.dumps({'body': sys.stdin.read()}))" <<< "$body")

  if [ -n "$existing_id" ]; then
    curl -sf \
      -X PATCH \
      -H "Authorization: Bearer $token" \
      -H "Accept: application/vnd.github+json" \
      "${API_URL}/repos/${repo}/issues/comments/${existing_id}" \
      -d "$json_body" > /dev/null
    echo "oobo-ci: updated GitHub comment"
  else
    curl -sf \
      -X POST \
      -H "Authorization: Bearer $token" \
      -H "Accept: application/vnd.github+json" \
      "${API_URL}/repos/${repo}/issues/${pr}/comments" \
      -d "$json_body" > /dev/null
    echo "oobo-ci: posted GitHub comment"
  fi
}

# ── Post comment to GitLab ───────────────────────────────────────────────

post_gitlab_comment() {
  local token="$1" project="$2" mr="$3" body="$4" tag="$5"

  local notes_url="${API_URL}/projects/${project}/merge_requests/${mr}/notes"

  local existing_id
  existing_id=$(curl -sf \
    -H "PRIVATE-TOKEN: $token" \
    "${notes_url}?per_page=100" \
    | python3 -c "
import sys, json
notes = json.load(sys.stdin)
for n in notes:
    if '${tag}' in n.get('body', ''):
        print(n['id'])
        break
" 2>/dev/null || true)

  local encoded_body
  encoded_body=$(python3 -c "import sys,urllib.parse; print(urllib.parse.quote(sys.stdin.read()))" <<< "$body")

  if [ -n "$existing_id" ]; then
    curl -sf -X PUT \
      -H "PRIVATE-TOKEN: $token" \
      --data "body=${encoded_body}" \
      "${notes_url}/${existing_id}" > /dev/null
    echo "oobo-ci: updated GitLab MR note"
  else
    curl -sf -X POST \
      -H "PRIVATE-TOKEN: $token" \
      --data "body=${encoded_body}" \
      "${notes_url}" > /dev/null
    echo "oobo-ci: posted GitLab MR note"
  fi
}

# ── Main ─────────────────────────────────────────────────────────────────

main() {
  install_oobo

  local platform
  platform=$(detect_platform)
  echo "oobo-ci: detected platform: $platform"

  extract_pr_metadata "$platform"

  if [ -z "$PR_NUMBER" ]; then
    echo "oobo-ci: not a pull request build — skipping"
    exit 0
  fi

  # Fetch the anchor branch
  git fetch origin oobo/anchors/v1:oobo/anchors/v1 2>/dev/null || true

  # Generate markdown
  local body
  body=$(oobo pr --base "origin/${BASE_REF}" --head HEAD 2>/dev/null || true)

  if [ -z "$body" ]; then
    echo "oobo-ci: no AI context found — skipping"
    exit 0
  fi

  local tag="<!-- oobo-pr-summary -->"

  # Resolve the API token
  local token=""
  if [ "$API_TYPE" = "github" ]; then
    token="${GITHUB_TOKEN:-${GH_TOKEN:-}}"
  elif [ "$API_TYPE" = "gitlab" ]; then
    token="${GITLAB_TOKEN:-}"
  fi

  if [ -z "$token" ]; then
    echo "oobo-ci: no API token available — printing summary to stdout"
    echo ""
    echo "$body"
    exit 0
  fi

  # Post the comment
  if [ "$API_TYPE" = "github" ]; then
    post_github_comment "$token" "$REPO_SLUG" "$PR_NUMBER" "$body" "$tag"
  elif [ "$API_TYPE" = "gitlab" ]; then
    post_gitlab_comment "$token" "$REPO_SLUG" "$PR_NUMBER" "$body" "$tag"
  fi
}

main "$@"
